# Generated by Django 2.2.17 on 2021-03-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastral', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('doc', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(db_index=True, verbose_name='Дата публикации'),
        ),
    ]
