# Generated by Django 2.2.17 on 2021-03-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastral', '0003_auto_20210309_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='doc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
